---
- name: configuring web server
  hosts: db
  tasks:
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: start webserver
    service:
      name: apache2.service
      enabled: yes
      state: started

  - name: enable firewall port
    community.general.ufw:
      rule: allow
      port: '80:85'
      proto: tcp

  - name: copy index.html
    copy:
      src: /yamls/index.html
      dest: /var/www/html
      mode: '0644'


...
